In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.4.0+cu121


## Introducion to Tensors

### Creating tensors

In [3]:
# scalar
scalar = torch.tensor(7)
print(scalar)
print(scalar.ndim)
# Get tensor back as Python int
print(scalar.item())

tensor(7)
0
7


In [4]:
# Vector
vector = torch.tensor([7,7])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([7, 7])
1
torch.Size([2])


In [5]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX.shape)

tensor([[ 7,  8],
        [ 9, 10]])
2
torch.Size([2, 2])


In [6]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])
3
torch.Size([1, 3, 3])


### Random tensors

In [7]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.5517, 0.0381, 0.6343, 0.9491],
        [0.8220, 0.1397, 0.8596, 0.9932],
        [0.1891, 0.5049, 0.0829, 0.7655]])

In [8]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [9]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [10]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating range of tensors and tensors-like

In [11]:
# Use torch.range()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [13]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None,
                                                device=None,
                                                requires_grad=False)
print(float_32_tensor)
print(float_32_tensor.dtype)

tensor([3., 6., 9.])
torch.float32


In [14]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

### Getting information from tensors

In [15]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.5054, 0.8432, 0.5796, 0.8863],
        [0.9039, 0.9136, 0.1821, 0.5399],
        [0.2271, 0.0032, 0.4121, 0.2804]])

In [16]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.5054, 0.8432, 0.5796, 0.8863],
        [0.9039, 0.9136, 0.1821, 0.5399],
        [0.2271, 0.0032, 0.4121, 0.2804]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

In [17]:
tensor = torch.tensor([1, 2, 3])
print(tensor + 10) #torch.add(tensor, 10)
print(tensor * 10) #torch.mul(tensor, 10)
print(tensor - 10)

tensor([11, 12, 13])
tensor([10, 20, 30])
tensor([-9, -8, -7])


### Matrix multiplication

In [18]:
# Element wise multiplication
print(tensor , "*", tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [19]:
# Matrix multiplication (torch.mm)
print(torch.matmul(tensor, tensor))
print(torch.matmul(torch.rand(4,2), torch.rand(2,4)))

tensor(14)
tensor([[0.4153, 0.4352, 0.3187, 0.8712],
        [0.3654, 0.0164, 0.3399, 0.4979],
        [0.0848, 0.0136, 0.0773, 0.1227],
        [0.0886, 0.0976, 0.0672, 0.1893]])


### Finding the min, max, mean, sum, etc (tensor aggregation)

In [29]:
# Create a tensor
x = torch.arange(1, 100, 10)
print(x, x.dtype)
print(torch.min(x), x.min())
print(torch.max(x), x.max())
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
print(torch.mean(x.type(torch.float32)), x.type(torch.float32).mean())
print(torch.sum(x), x.sum())

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]) torch.int64
tensor(1) tensor(1)
tensor(91) tensor(91)
tensor(46.) tensor(46.)
tensor(460) tensor(460)


### Finding the positional min and max

In [31]:
print(x)
# Find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where the minimum value occurs
print(x.argmin())
print(x.argmax())

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])
tensor(0)
tensor(9)


### Reshaping, stacking, squeezing, and unsqueezing tensors

In [40]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
print(x_reshaped, x_reshaped.shape)
print("--------------------")

# Change the view
z = x.view(1, 9)
print(z, z.shape)
z[:,0] = 5
print(z, x)

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]) torch.Size([1, 9])
--------------------
tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]) torch.Size([1, 9])
tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]) tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])


In [48]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# torch.squeeze()
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")


Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [54]:
# torch.unsqeeze()
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

x_unsqueezed = x_squeezed.squeeze()
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [ ]:
# torch.permute()
x_original = torch.rand(size=(224, 224, 3)) # [height, width, color_channels]

x_permuted = x_original.permute(2, 0, 1)
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") 

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])
