In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.4.0+cu121


## Introducion to Tensors

### Creating tensors

In [2]:
# scalar
scalar = torch.tensor(7)
print(scalar)
print(scalar.ndim)
# Get tensor back as Python int
print(scalar.item())

tensor(7)
0
7


In [3]:
# Vector
vector = torch.tensor([7,7])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([7, 7])
1
torch.Size([2])


In [4]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX.shape)

tensor([[ 7,  8],
        [ 9, 10]])
2
torch.Size([2, 2])


In [5]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])
3
torch.Size([1, 3, 3])


### Random tensors

In [6]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.1041, 0.3152, 0.0910, 0.7559],
        [0.6756, 0.6210, 0.6176, 0.9008],
        [0.4781, 0.5879, 0.1784, 0.9382]])

In [7]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [8]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [9]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating range of tensors and tensors-like

In [10]:
# Use torch.range()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [12]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None,
                                                device=None,
                                                requires_grad=False)
print(float_32_tensor)
print(float_32_tensor.dtype)

tensor([3., 6., 9.])
torch.float32


In [13]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

### Getting information from tensors

In [14]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.2638, 0.9343, 0.6361, 0.1681],
        [0.4509, 0.5452, 0.0129, 0.7451],
        [0.2302, 0.0942, 0.2164, 0.4195]])

In [15]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.2638, 0.9343, 0.6361, 0.1681],
        [0.4509, 0.5452, 0.0129, 0.7451],
        [0.2302, 0.0942, 0.2164, 0.4195]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

In [16]:
tensor = torch.tensor([1, 2, 3])
print(tensor + 10) #torch.add(tensor, 10)
print(tensor * 10) #torch.mul(tensor, 10)
print(tensor - 10)

tensor([11, 12, 13])
tensor([10, 20, 30])
tensor([-9, -8, -7])


### Matrix multiplication

In [17]:
# Element wise multiplication
print(tensor , "*", tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix multiplication (torch.mm)
print(torch.matmul(tensor, tensor))
print(torch.matmul(torch.rand(4,2), torch.rand(2,4)))

tensor(14)
tensor([[0.1136, 0.1888, 0.0261, 0.1470],
        [0.5997, 0.8414, 0.1482, 0.5592],
        [0.5372, 0.9625, 0.1190, 0.7916],
        [0.4091, 0.5822, 0.1005, 0.3929]])
